// action 类型

const ActionType = {

  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  UPDATE_USER_LOGIN: 'UPDATE_USER_LOGIN',
  UPDATE_USER_LOGIN_UID: 'UPDATE_USER_LOGIN_UID',

  UPDATE_SHARE_INFO: 'UPDATE_SHARE_INFO',

  UPDATE_UNREAD_INFO: 'UPDATE_UNREAD_INFO',
  UPDATE_COMMENT_UNREAD: 'UPDATE_COMMENT_UNREAD',
  UPDATE_QUOTE_UNREAD: 'UPDATE_QUOTE_UNREAD',
  UPDATE_SYS_UNREAD: 'UPDATE_SYS_UNREAD',

  CHANGE_ACTIVE_INDEX: 'CHANGE_ACTIVE_INDEX',
  CHANGE_HOME_SELECTED_INDEX: 'CHANGE_HOME_SELECTED_INDEX',
  CHANGE_HOME_SCROLL_TOP: 'CHANGE_HOME_SCROLL_TOP',
  CHANGE_HOME_CUR_PAGE: 'CHANGE_HOME_CUR_PAGE',
  UPDATE_FINANCE_ROLL: 'UPDATE_FINANCE_ROLL',
  UPDATE_HOT_LIST: 'UPDATE_HOT_LIST',
  APPEND_HOT_LIST: 'APPEND_HOT_LIST',
  UPDATE_RECOMMEND_LIST: 'UPDATE_RECOMMEND_LIST',
  APPEND_RECOMMEND_LIST: 'APPEND_RECOMMEND_LIST',
  UPDATE_NEWEST_LIST: 'UPDATE_NEWEST_LIST',
  APPEND_NEWEST_LIST: 'APPEND_NEWEST_LIST',
  UPDATE_SECTION_DATA: 'UPDATE_SECTION_DATA',
  UPDATE_HOME_AD: 'UPDATE_HOME_AD',
  UPDATE_CHEST_INFO: 'UPDATE_CHEST_INFO',

  CHANGE_MSG_SELECTED_INDEX: 'CHANGE_MSG_SELECTED_INDEX',
  CHANGE_MSG_SCROLL_TOP: 'CHANGE_MSG_SCROLL_TOP',
  CHANGE_MSG_CUR_PAGE: 'CHANGE_MSG_CUR_PAGE',
  UPDATE_MSG_COMMENT_LIST: 'UPDATE_MSG_COMMENT_LIST',
  APPEND_MSG_COMMENT_LIST: 'APPEND_MSG_COMMENT_LIST',
  UPDATE_MSG_POST_LIST: 'UPDATE_MSG_POST_LIST',
  APPEND_MSG_POST_LIST: 'APPEND_MSG_POST_LIST',
  UPDATE_MSG_PRIVATE_LIST: 'UPDATE_MSG_PRIVATE_LIST',
  APPEND_MSG_PRIVATE_LIST: 'APPEND_MSG_PRIVATE_LIST',

  CHANGE_SECTION_SELECTED_INDEX: 'CHANGE_SECTION_SELECTED_INDEX',
  CHANGE_SECTION_SCROLL_TOP: 'CHANGE_SECTION_SCROLL_TOP',
  CHANGE_SECTION_CUR_PAGE: 'CHANGE_SECTION_CUR_PAGE',
  UPDATE_SECTION_THREAD_LIST: 'UPDATE_SECTION_THREAD_LIST',
  APPEND_SECTION_THREAD_LIST: 'APPEND_SECTION_THREAD_LIST',


  // UPDATE_HOME_SLIDES: 'UPDATE_HOME_SLIDES',
  // UPDATE_HOME_SECTIONS: 'UPDATE_HOME_SECTIONS',

  CHANGE_HEAD_TITLE: 'CHANGE_HEAD_TITLE',
  // CHANGE_NAV: 'CHANGE_NAV',
  // UPDATE_LIST_DATA: 'UPDATE_LIST_DATA',
  // APPEND_TO_HOME_LIST: 'APPEND_TO_HOME_LIST',
  // CHANGE_HOME_CUR_PAGE: 'CHANGE_CUR_PAGE',
  // CHANGE_HOME_CUR_TOP: 'CHANGE_HOME_CUR_TOP',

  UPDATE_FINANCE_ROLL: 'UPDATE_FINANCE_ROLL',
  UPDATE_FINANCE_LIST: 'UPDATE_FINANCE_LIST',
  APPEND_TO_FINANCE_LIST: 'APPEND_TO_FINANCE_LIST',
  CHANGE_FINANCE_CUR_PAGE: 'CHANGE_FINANCE_CUR_PAGE',
  CHANGE_FINANCE_CUR_TOP: 'CHANGE_FINANCE_CUR_TOP'
};

export default ActionType;